### ISSUE TITLE
Connecting to remote device through DNS

### ISSUE THREAD

**Issue by ArturoS21** [virtualheart/ZKteco-biomatric-lib#2]
Hi!
Is it possible to connect to a remote device linked to a dns and port 4370 opened? I already tried but it seems to take too long or the program seems freeze.

**Comment by virtualheart** [comment]
Hi @ArturoS21,

Here is some troubleshooting you can try.

1. Port Forwarding: Ensure that the remote router's settings are configured to forward port 4370 to the internal IP address of the ZKTeco device. Verify that both the router and firewall allow this port to handle incoming and outgoing connections for external access.

2. Execution Timeout: Implement a timeout setting in your code for the UDP connection. This will prevent your program from hanging if the device doesn't respond. Consider using a retry mechanism with a delay to handle intermittent failures.

3. Ping the Device: Use the ping command to check if the DNS resolves correctly and if there’s connectivity between your system and the device. If the device doesn’t support ping, you could also test connectivity using a different protocol (e.g., netcat or telnet) to check if the port is open.

4. Check Device Logs: If logs are available on the ZKTeco device, review them for any sign of connection attempts or errors. Alternatively, change the device IP to your system IP temporarily, and use netcat -lvp 4370 to listen on that port. This will help capture any UDP packets sent by your program to see if data is being transmitted properly.

5. Firewall Settings: Ensure that both the client and server's firewalls are configured to allow incoming and outgoing traffic on port 4370 for UDP. This includes checking network security rules that might block UDP traffic.

6. Enable Debugging: In your program, enable debugging or logging to track where the issue occurs. You can log the request, response times, and any potential errors encountered. This will help pinpoint whether the issue lies in the connection, timeout, or response handling.
